name: Lint
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Lint app
      - name: Lint app
        run: ./gradlew lintDebug


